Replace `send_onchain` snippets with `pay_onchain`
breez/breez-sdk-docs pull request #144
Opened 2024-03-14 18:12 UTC by ok300

This PR replaces the old `send_onchain` call in snippets with `pay_onchain`.

2024-03-14 21:20 UTC, dangeross requested changes

2024-03-14 21:20 UTC, dangeross commented on snippets/go/send_onchain.go
> +	}
Fix CI
```suggestion
	payOnchainRequest := breez_sdk.PayOnchainRequest{
		RecipientAddress: destinationAddress,
		PrepareRes:       prepareRes,
	}
```

2024-03-14 21:20 UTC, dangeross commented on snippets/react-native/send_onchain.ts
Need to add the imports for the CI to pass:
```
import {
  type OnchainPaymentLimitsResponse,
  type PrepareOnchainPaymentResponse,
  fetchReverseSwapFees,
  inProgressReverseSwaps,
  onchainPaymentLimits,
  payOnchain,
  prepareOnchainPayment,
  SwapAmountType,
  maxReverseSwapAmount
} from '@breeztech/react-native-breez-sdk'
```

2024-03-14 21:20 UTC, dangeross commented on snippets/dart_snippets/lib/send_onchain.dart
>    return resp;
To fix CI
```suggestion
  return res;
```

2024-03-14 21:20 UTC, dangeross commented on snippets/dart_snippets/lib/send_onchain.dart
>    return resp;
```suggestion
  return prepareRes;
```

2024-03-14 21:20 UTC, dangeross commented on snippets/react-native/send_onchain.ts
> +const examplePayOnchain = async (prepareResponse: PrepareOnchainPaymentResponse) => {
```suggestion
const examplePayOnchain = async (prepareRes: PrepareOnchainPaymentResponse) => {
```

2024-03-14 21:20 UTC, dangeross commented on snippets/react-native/send_onchain.ts
> +      prepareResponse
```suggestion
      prepareRes
```

2024-03-14 21:29 UTC, dangeross commented on snippets/python/src/send_onchain.py
The return variable needs changing to `current_limits` for get_current_limits:
```
def get_current_limits(sdk_services):
    try: 
        # ANCHOR: get-current-reverse-swap-limits
        current_limits = sdk_services.onchain_payment_limits()
        print("Minimum amount, in sats: ", current_limits.min_sat)
        print("Maximum amount, in sats: ", current_limits.max_sat)
        # ANCHOR_END: get-current-reverse-swap-limits
        return current_limits
    except Exception as error:
        print(error)
        raise
```

2024-03-14 22:57 UTC, erdemyerebasmaz commented on snippets/dart_snippets/lib/send_onchain.dart
Could rename this file to `pay_onchain.dart`

2024-03-15 09:54 UTC, ok300 commented on snippets/python/src/send_onchain.py
Done: c6e014b6cb12dfa9975937bd16bc458fd1fd1a2d

2024-03-15 09:56 UTC, ok300 commented on snippets/react-native/send_onchain.ts
Done: 3df4fc04d85a5ad96aca3e8c834861b644ed47e7

2024-03-15 10:00 UTC, ok300 commented on snippets/dart_snippets/lib/send_onchain.dart
Good idea. I added it as a separate step in https://github.com/breez/breez-sdk-docs/issues/140 to make it easier to review.

2024-03-15 10:31 UTC, ok300 commented
@dangeross @erdemyerebasmaz thanks for the findings, fixed them all. Ready for final review.

2024-03-15 11:21 UTC, dangeross approved these changes
LGTM

2024-03-15 17:24 UTC, erdemyerebasmaz approved these changes
LGTM

2024-03-15 18:06 UTC, merged