Swfit examples for fee calc and lsp connection
breez/breez-sdk-docs pull request #20
Opened 2023-07-12 11:09 UTC by ubbabeck

2023-07-12 18:04 UTC, ubbabeck commented
I have ran all the examples for python and swift, but not go. The reason for this is that I had some issues with my environment so the code did not run for some reason.

2023-07-12 20:06 UTC, roeierez approved these changes
LGTM

2023-07-12 20:26 UTC, dangeross requested changes
LGTM, just needs one small change

2023-07-12 20:26 UTC, dangeross commented on src/guide/receive_onchain.md
> +		return 0, fmt.Error("Channel not needed")
Should be `Errorf`

2023-07-12 23:21 UTC, erdemyerebasmaz commented on src/guide/receive_onchain.md
> +    // A setup fee of {setupFee} with a minimum of {minFee} will be applied for sending more than {liquidity}.
The percentage is not a typo, setup fee is the proportional fee, e.g. 7.5%

2023-07-13 07:05 UTC, ubbabeck commented on src/guide/receive_onchain.md
> +		return 0, fmt.Error("Channel not needed")
fixed

2023-07-13 07:20 UTC, dangeross approved these changes

2023-07-13 07:28 UTC, merged