Extract Go snippets
breez/breez-sdk-docs pull request #83
Opened 2023-11-06 15:25 UTC by erdemyerebasmaz

This PR adds Go snippets to
- #72

2023-11-06 19:44 UTC, JssDWt reviewed
left a few comments.

2023-11-06 19:44 UTC, JssDWt commented on snippets/go/go.sum
> +github.com/breez/breez-sdk-go v0.2.7 h1:9Kemh1y/T2y6y9eIR3ZYYbfYNQYyJ+UfyIoI8xmar90=
let's gitignore this file to make it easier to switch versions

2023-11-06 19:44 UTC, JssDWt commented on snippets/go/main.go
> +package main
There is a binary file called `main` committed

2023-11-06 19:44 UTC, JssDWt commented on snippets/go/send_payment.go
> +	amountMsat := uint64(3000000)
```suggestion
	amountMsat := uint64(3_000_000)
```

2023-11-06 19:44 UTC, JssDWt commented on snippets/go/send_onchain.go
> +	sendAmountSat := uint64(50000)
```suggestion
	sendAmountSat := uint64(50_000)
```

2023-11-06 19:44 UTC, JssDWt commented on snippets/go/send_onchain.go
> +	sendAmountSat := uint64(50000)
```suggestion
	sendAmountSat := uint64(50_000)
```

2023-11-06 19:44 UTC, JssDWt commented on snippets/go/receive_onchain.go
> +	amountMsat := uint64(10000)
this can be passed in as a parameter. Or make it 3_000_000.

2023-11-06 20:03 UTC, dangeross requested changes
Looks good, just a small anchor fix needed

2023-11-06 22:47 UTC, erdemyerebasmaz commented
Addressed feedback.
- Removed & added binary & dependency checksum files to .gitignore
- Added underscore as a separator in number literals
- Corrected get-channel-opening-fees anchor_end
- Farewell to "Hello World"

2023-11-07 09:08 UTC, JssDWt approved these changes
LGTM!

2023-11-07 09:14 UTC, dangeross approved these changes
🚀

2023-11-07 09:48 UTC, merged